rfc: enforcement steps in coc
WeAllJS/wealljs.github.io pull request #40
Opened 2016-12-17 20:52 UTC by zkat

This RFC proposes an update to our CoC and enforcement policies to make enforcement clearer to users.

2016-12-17 21:10 UTC, varjmes requested changes

2016-12-17 21:10 UTC, Charlotteis commented on _pages/rfc-unify-coc-enforcement.md
> +## tl;dr
Can we do 'In Summary' here, instead? :)

2016-12-17 21:10 UTC, Charlotteis commented on _pages/rfc-unify-coc-enforcement.md
> +The first thing people should see when they go to the CoC is how it affects them. The bulk of the stuff on the CoC itself amounts to legalese that most users won't read -- so in the interest of conve
"the main thing people even are about." missed a "c" on "are".

2016-12-17 21:10 UTC, Charlotteis commented on _pages/rfc-unify-coc-enforcement.md
> +Hopefully, these changes will make expectations even clearer for everone!
"everone" -> "everyone"

2016-12-17 21:10 UTC, Charlotteis commented on _pages/rfc-unify-coc-enforcement.md
> +1. Tell the person “hey, that’s not ok”.
I prefer something like "Let the person know that what they're doing is not appropriate"

2016-12-17 21:10 UTC, Charlotteis commented on _pages/rfc-unify-coc-enforcement.md
> +  * Direct Message [@WeAllJS](https://twitter.com/wealljs) on Twitter with the details and any relevant links.
Can we order these by which we'd prefer?

I'd like:

- /admin
- DM in Slack
- Email
- DM WeAllJs

2016-12-17 21:10 UTC, Charlotteis commented on _pages/rfc-unify-coc-enforcement.md
> +  4. If the behavior continues or is repeated after the temp deactivation, a long-term (6-12mo) deactivation will be used.
can we say "temporary" instead of "temp?". Just for language consistency 🤓

2016-12-17 21:17 UTC, cjoulain commented on _pages/rfc-unify-coc-enforcement.md
> +1. Tell the person “hey, that’s not ok”.
I know it's not easy for everyone but I do like that this encourages someone noticing a CoC violation be pro-active about commenting on it. Do you think this write-up should give examples? (For example, something along the lines of: "If you don't feel comfortable addressing a person who made a problematic remark in the channel, feel free to PM them.) I think it empowers the person noticing a remark to manage the situation and the conversation might not need to be escalated to admin.

2016-12-18 05:07 UTC, zkat commented
@Charlotteis @cjoulain updated! lmk what you think. I added a whole examples section

2016-12-19 09:53 UTC, varjmes approved these changes

2016-12-19 09:53 UTC, Charlotteis commented
:shipit: 😻

2016-12-19 17:45 UTC, merged

2016-12-19 17:46 UTC, jenniferlynparsons commented on _pages/enforcement.md
> +say Some Shit:tm: and things are going to go awry. This document is meant as a
Is the profanity okay? The document is fairly informal, but I'm not sure exactly how informal it should be.

2016-12-19 17:56 UTC, zkat commented on _pages/enforcement.md
> +say Some Shit:tm: and things are going to go awry. This document is meant as a
I don't know. To me, that's an undirected phrase that hopefully adds a hint of levity to a more serious document. I'm happy to change it though.

2016-12-19 17:58 UTC, jenniferlynparsons commented on _pages/enforcement.md
> +say Some Shit:tm: and things are going to go awry. This document is meant as a
That's pretty much how I react to it as well, and have no personal problem with it staying in.