Abstract over examples of abuse
WeAllJS/wealljs.github.io pull request #43
Opened 2017-01-05 22:17 UTC by deeglaze

Including aggressive and explicitly abusive language is counter-productive to a CoC's mission to model good behavior and give the abused actions of recourse.

2017-01-05 22:33 UTC, zkat approved these changes
I like this! I'll let one or two other folks get some eyeballs on it, but this LGTM. Thank you!

2017-01-05 22:36 UTC, cjwilburn commented on _pages/code-of-conduct.md
> +> Alex: "Yeah I used X and it was [negative association with mental health]"
Nice. Good point that including the language itself can server to unnecessarily re-traumatize.

2017-01-05 22:37 UTC, cjwilburn approved these changes
LGTM. Thanks for bringing this up.

2017-01-06 09:49 UTC, AgentAntelope commented on _pages/code-of-conduct.md
> +> Patt: "Leave me alone I haven't said anything bad [aggressive jab]."
I think that [aggressive jab] here isn't even required; rejecting MxAdmin1's comments would be bad enough without attacking the admin.

2017-01-06 11:53 UTC, Charlotteis commented on _pages/code-of-conduct.md
> +> Alex: "Yeah I used X and it was [negative association with mental health]"
Many many people wouldn't know that kind of words that would involve, so could we link to this document: https://wealljs.org/rfc-slackbot-language-shorthands?

I know that you don't want us to use these words in our documentation (i agree), but people need to know what we dont tolerate and mental health slurs are so ingrained in our culture.

2017-01-06 11:54 UTC, varjmes requested changes

2017-01-06 11:54 UTC, Charlotteis commented on _pages/code-of-conduct.md
> +> Alex: "Yeah I used X and it was [negative association with mental health]"
Many many people wouldn't know that kind of words that would involve, so could we link to this document: https://wealljs.org/rfc-slackbot-language-shorthands?

I know that you don't want us to use these words in our documentation (i agree), but people need to know what we dont tolerate and mental health slurs are so ingrained in our culture.

2017-01-08 20:07 UTC, cjoulain requested changes
@deeglaze We definitely want to be mindful with language. Several of these suggested changes would remove the context from these scenarios (for instance line 99/Alex's statement). Those unfamiliar with how certain charged words stigmatize mental health will not know what is being discussed. I agree with Charlotte's suggestion of linking to the Slackbot shorthands. That way, folks can educate themselves on being more careful with the language they use.

2025-07-01 21:23 UTC, closed without merging